import type { Metadata } from "next";
import { Geist, Geist_Mono, Poetsen_One, Yellowtail } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const yellowtail = Yellowtail({
  variable: "--font-yellowtail",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap"
});

const poetsen = Poetsen_One({
  variable: "--font-poetsenone",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Cumplendary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${yellowtail.variable} ${poetsen.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
